[workspace]
[package]
name = "openvm-client-eth"
description = ""
edition = "2021"

[dependencies]
rustc-hash = "2.1.0"

# workspace
openvm-client-executor = { path = "../../crates/executor/client" }

revm-precompile = { version = "11.0.1", default-features = false, features = [
    "openvm-k256",
    "openvm-bn",
] }

# openvm
openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3", features = [
    "std",
] }
openvm-platform = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-keccak256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-algebra-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-algebra-moduli-macros = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-algebra-complex-macros = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-ecc-sw-macros = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3" }
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3", features = [
    "k256",
] }
openvm-bigint-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3", features = [
    "export-intrinsics",
] }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "30576cc6ce838f213bf05b2e4ad035d95498c8b3", features = [
    "bn254",
] }

# Statically turns off logging
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
tracing = { version = "0.1", features = [
    "max_level_off",
    "release_max_level_off",
] }

serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tendermint = { version = "=0.40.1", default-features = false }
tendermint-light-client-verifier = { version = "=0.40.1", default-features = false, features = [
    "rust-crypto",
] }

[features]
default = []
heap-embedded-alloc = ["openvm/heap-embedded-alloc"]

[patch.crates-io]
revm = { git = "https://github.com/axiom-crypto/revm", branch = "v43-openvm" }
revm-primitives = { git = "https://github.com/axiom-crypto/revm", branch = "v43-openvm" }
revm-interpreter = { git = "https://github.com/axiom-crypto/revm", branch = "v43-openvm" }
revm-precompile = { git = "https://github.com/axiom-crypto/revm", branch = "v43-openvm" }
ruint = { git = "https://github.com/axiom-crypto/uint", branch = "v1.12.3-openvm" }
# revm = { path = "../../../revm/crates/revm" }
# revm-primitives = { path = "../../../revm/crates/primitives" }
# revm-interpreter = { path = "../../../revm/crates/interpreter" }
# revm-precompile = { path = "../../../revm/crates/precompile" }

[profile.release]
panic = "abort"
lto = "fat"
strip = true

[profile.profiling]
inherits = "release"
debug = 2
strip = false
